---

- name: Ensure hostname is resolvable
  become: yes
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 localhost {{ ansible_hostname }}"
    regexp: ^127\.0\.0\.1
  when: ansible_virtualization_type != "docker"

- name: Install essential packages
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items: "{{ sansible_gocd_agent_packages }}"

- name: Install AWS CLI, boto
  become: yes
  pip:
    name: "{{ item }}"
  with_items:
    - awscli
    - boto
  when: sansible_gocd_agent_aws_install_cli == true

- name: Add GoCD Apt key
  become: yes
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: "{{ sansible_gocd_agent_repo_key_id }}"
    state: present

- name: Install GoCD repo
  become: yes
  apt_repository:
    repo: "{{ sansible_gocd_agent_repo_source }}"
    state: present
    update_cache: yes

- name: Install go-agent
  become: yes
  apt:
    name: "go-agent={{ sansible_gocd_agent_version | regex_replace('^(.*?)\\*?$', '\\1*') }}"
    state: present
    force: yes

- name: Ensure that the default agent is stopped and disabled
  become: yes
  service:
    enabled: no
    name: go-agent
    state: stopped
