---

- name: Converge
  hosts: all

  pre_tasks:
    - name: Force a SystemD process so GoCD Agent installer correctly detects SystemD
      become: yes
      shell: >-
        set -e && \
        pidof systemd || systemd --user > /dev/null 2>&1 &
      environment:
        XDG_RUNTIME_DIR: /tmp
      changed_when: no
      tags:
        - skip_ansible_lint

  roles:
    - role: gocd_agent
      sansible_gocd_agent_aws_profiles:
        - name: testProfile
          config:
            role_arn: "arn::::"
            source_profile: default
            s3:
              max_queue_size: 1000
