---

- name: Converge
  hosts: all

  roles:
    - role: gocd_agent
      sansible_gocd_agent_aws_profiles:
        - name: testProfile
          config:
            role_arn: "arn::::"
            source_profile: default
            s3:
              max_queue_size: 1000
